revert vulkan.msm8998.so to 3be114a4d1893663ec25ba2472954f7ab6fe4432
vulkan.msm8998.so from 051ade8a02f95b313485a4488fc2d5c4da8a8283 is
incompatible with the shader compiler

No idea where that vulkan.msm8998.so came from, it probably needs
it's full adreno stack imported to work, instead of just that lib

Fixes the following:
11-24 12:46:50.609  8102  8124 I AdrenoVK: Shader compilation failed for shaderType: 0
11-24 12:46:50.609  8102  8124 I AdrenoVK: Info log: ERROR: 0:1: '' : Unknown char
11-24 12:46:50.609  8102  8124 I AdrenoVK: INTERNAL ERROR: no main() function!
11-24 12:46:50.609  8102  8124 I AdrenoVK: ERROR: 1 compilation errors.  No code generated.
11-24 12:46:50.609  8102  8124 I AdrenoVK:
11-24 12:46:50.609  8102  8124 I AdrenoVK:

Change-Id: I8dfb6603cf61bc647da0222f13a1179d019acee9